name: Deploy to vnba.edu.vn

on:
  push:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Using latest LTS version of Node
          cache: 'npm' # Caching npm dependencies
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and Export
        run: |
          npm run build
          # Assuming your next.config.js has output: 'export' set
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          # Next.js static export puts files in the 'out' directory
          rsync -avz --delete ./out/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/vnba.edu.vn/html/ 