name: Deploy to Production

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build static site
        run: |
          npm run build
          echo "Build completed, checking output directory:"
          ls -la ./out
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 112.78.3.202 >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./out/ deploy@112.78.3.202:/var/www/vnba.edu.vn/html/
      
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          curl -s -o /dev/null -w "%{http_code}" https://vnba.edu.vn || echo "Site may not be accessible yet" 