name: Deploy Coming Soon Page

on:
  push:
    branches:
      - comingsoon
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Debug - Check Next.js config
        run: cat next.config.ts

      - name: Build with Next.js
        run: |
          npm run build
          # Create out directory if it doesn't exist (fallback)
          mkdir -p out
        env:
          NEXT_PUBLIC_BASE_PATH: ''
          NODE_ENV: production

      - name: Debug - List files
        run: |
          echo "Workspace contents:"
          ls -la
          echo "Content of .next directory:"
          ls -la .next || echo ".next directory does not exist"
          echo "Content of out directory:"
          ls -la out || echo "out directory does not exist"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 