name: Deploy Coming Soon Page

on:
  push:
    branches:
      - comingsoon
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Debug - Check Next.js config
        run: cat next.config.ts

      - name: Build with Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: ''
          NODE_ENV: production

      - name: Ensure index.html exists
        run: |
          ls -la out
          if [ ! -f out/index.html ]; then
            echo "Warning: index.html not found in out directory"
            # Create a simple index.html as a fallback
            if [ -f out/comingsoon/index.html ]; then
              echo "Copying comingsoon/index.html to root as fallback"
              cp out/comingsoon/index.html out/index.html
            fi
          fi

      - name: Debug - List files
        run: |
          echo "Workspace contents:"
          ls -la
          echo "Content of out directory:"
          ls -la out
          echo "Checking root index.html:"
          if [ -f out/index.html ]; then
            echo "✅ index.html exists at root"
          else
            echo "❌ index.html is missing from root"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 